### ISSUE TITLE
Tool workflows for automating pentests

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/reptor#42]
Pentests often have parts that can easily be automated. Some tools could be automatically triggered, parsed, and added as issue to a report.

#41 would allow us to protocol commands and their outputs.

We could use this feature to implement workflows. A workflow is a definition of commands that should be executed.

```
---
upload: yes
parallel_execution: yes
commands:
  - sudo nmap -p 80 {target}
  - nuclei -t xyz- -u {target}
  - sslyze -u {target}
```

The workflow could be executed (`reptor cmd --workflow wf.yaml`), the tools run and upload their tool outputs to the current report.

(Regarding parallelization, we could also introduce stages that should run in parallel.)
```
---
upload: yes
parallel_execution: yes
commands:
  portscan:
    - sudo nmap -p 80 {target}
  attacks:
    - nuclei -t xyz- -u {target}
    - sslyze -u {target}
```

In the future, we could also take tool outputs from previous tools (like sslyze open ssl ports from nmap scan).
